-- Deprecated compatibility marker.
-- Database DDL is managed by ordered migrations in apps/api/migrations.
-- Apply them explicitly with:
--   MIGRATION_DATABASE_URL=... npm run migrate:up --workspace @firecrawl/api
-- The API never executes this file during startup.
