export interface NeedsCloudResult { required: boolean; reason: string; }
export type GatewayRequestRejection = { statusCode: 400 | 403 | 404 | 413; reason: string };

const validRouteModes = new Set(["self-hosted-first", "self-hosted-only", "cloud-first", "cloud-only"]);
const cloudOnlyPathPatterns = [/^\/v\d+\/agent(?:\/|$)/, /^\/v\d+\/browser(?:\/|$)/, /^\/v\d+\/monitor(?:\/|$)/, /^\/v\d+\/search\/research(?:\/|$)/, /^\/v\d+\/research(?:\/|$)/, /^\/v\d+\/support(?:\/|$)/, /^\/v\d+\/team(?:\/|$)/, /^\/v\d+\/feedback(?:\/|$)/, /^\/v\d+\/scrape\/[^/]+\/interact(?:\/|$)/, /^\/v\d+\/search\/[^/]+\/feedback(?:\/|$)/];

export function getRouteMode(reqUrl: string, headers: Record<string, string | string[] | undefined>, defaultRouteMode: string): string { const headerMode = String(headers["x-firecrawl-route-mode"] || "").trim(); if (validRouteModes.has(headerMode)) return headerMode; const queryMode = new URL(reqUrl, "http://gateway.local").searchParams.get("routeMode"); if (queryMode && validRouteModes.has(queryMode)) return queryMode; return validRouteModes.has(defaultRouteMode) ? defaultRouteMode : "cloud-first"; }
export function hasSensitiveHeaders(headers: Record<string, string | string[] | undefined>, jsonBody: unknown): boolean { if (Object.keys(headers).some((key) => ["authorization", "cookie"].includes(key.toLowerCase()))) return true; for (const item of findObjectsByKey(jsonBody, "headers")) if (item && typeof item === "object" && !Array.isArray(item) && Object.keys(item).some((key) => { const lower = key.toLowerCase(); return lower === "authorization" || lower === "cookie" || lower === "x-api-key" || lower.includes("token") || lower.includes("secret"); })) return true; return false; }
export function requestNeedsCloud(pathname: string, jsonBody: unknown): NeedsCloudResult { for (const pattern of cloudOnlyPathPatterns) if (pattern.test(pathname)) return { required: true, reason: "path requires a Firecrawl Cloud managed feature" }; let reason = ""; walk(jsonBody, (value) => { if (reason || !value || typeof value !== "object" || Array.isArray(value)) return; const record = value as Record<string, unknown>; if (Array.isArray(record.actions) && record.actions.length > 0) reason = "actions require Fire-engine-backed Cloud behavior"; else if (record.agent) reason = "agent extraction is Cloud-managed"; else if (Array.isArray(record.enterprise) && record.enterprise.length > 0) reason = "enterprise search options require Firecrawl Cloud"; else if (record.proxy === "stealth" || record.proxy === "enhanced") reason = "stealth/enhanced proxy requires Cloud-managed behavior"; }); return { required: Boolean(reason), reason }; }
export function chooseInitialBackend(routeMode: string, needsCloud: NeedsCloudResult): string { if (routeMode === "cloud-first" || routeMode === "cloud-only") return "cloud"; if (routeMode === "self-hosted-only") return needsCloud.required ? "reject" : "self-hosted"; return needsCloud.required ? "cloud" : "self-hosted"; }
export function isFallbackAllowed(routeMode: string, privacy: { hasSensitiveHeaders: boolean; hasPrivateTargetUrl: boolean }): boolean { return routeMode === "self-hosted-first" && !privacy.hasSensitiveHeaders && !privacy.hasPrivateTargetUrl; }
export function hasPrivateTargetUrl(value: unknown): boolean { let privateTarget = false; walk(value, (candidate) => { if (privateTarget || typeof candidate !== "string" || !/^https?:\/\//i.test(candidate)) return; try { const host = new URL(candidate).hostname.toLowerCase().replace(/^\[|\]$/g, ""); const ip = host.match(/^(\d+)\.(\d+)\.(\d+)\.(\d+)$/); privateTarget = host === "localhost" || host.endsWith(".localhost") || host.endsWith(".local") || host.endsWith(".internal") || host === "::1" || (ip !== null && (Number(ip[1]) === 10 || Number(ip[1]) === 127 || (Number(ip[1]) === 172 && Number(ip[2]) >= 16 && Number(ip[2]) <= 31) || (Number(ip[1]) === 192 && Number(ip[2]) === 168) || (Number(ip[1]) === 169 && Number(ip[2]) === 254))); } catch { /* validation handles malformed URLs separately */ } }); return privateTarget; }
export function isCloudQuotaFallbackAllowed(routeMode: string, needsCloud: NeedsCloudResult): boolean { return routeMode === "cloud-first" && !needsCloud.required; }
export function isSupportedFirecrawlPath(pathname: string): boolean { return /^\/v[12]\/[^/]+(?:\/|$)/.test(pathname); }
export function tokenScopeAllowsPath(scopes: string[] | null | undefined, pathname: string): boolean { if (!scopes || scopes.includes("*")) return true; const match = pathname.match(/^\/(v[12])\/([^/?]+)/); return Boolean(match && (scopes.includes(`${match[1]}:*`) || scopes.includes(`${match[1]}:${match[2]}`))); }

export function validateGatewayRequest(pathname: string, body: unknown): GatewayRequestRejection | null {
  if (!isSupportedFirecrawlPath(pathname)) return { statusCode: 404, reason: "Only /v1/* and /v2/* Firecrawl paths are supported" };
  let rejection: GatewayRequestRejection | null = null;
  walk(body, (value) => { if (rejection) return; if (typeof value === "string") { if (Buffer.byteLength(value, "utf8") > 1_048_576) rejection = { statusCode: 413, reason: "Request contains a string that exceeds the gateway limit" }; else if (/^[a-z][a-z\d+.-]*:\/\/\S+$/i.test(value)) { try { if (!["http:", "https:"].includes(new URL(value).protocol)) rejection = { statusCode: 400, reason: "Only HTTP(S) target URLs are allowed" }; } catch { rejection = { statusCode: 400, reason: "Request contains an invalid target URL" }; } } } if (Array.isArray(value) && value.length > 1_000) rejection = { statusCode: 413, reason: "Request contains too many array items" }; });
  if (rejection) return rejection;
  if (/\/v[12]\/(crawl|batch-scrape)(?:\/|$)/.test(pathname) && body && typeof body === "object" && !Array.isArray(body)) { const record = body as Record<string, unknown>; if (typeof (record.maxPages ?? record.limit) === "number" && Number(record.maxPages ?? record.limit) > 10_000) return { statusCode: 413, reason: "Requested crawl page count exceeds the gateway limit" }; if (typeof record.maxDepth === "number" && record.maxDepth > 10) return { statusCode: 413, reason: "Requested crawl depth exceeds the gateway limit" }; }
  if (/\/v[12]\/browser(?:\/|$)/.test(pathname) && body && typeof body === "object" && !Array.isArray(body) && typeof (body as Record<string, unknown>).ttl === "number" && Number((body as Record<string, unknown>).ttl) > 3_600) return { statusCode: 413, reason: "Requested browser TTL exceeds the gateway limit" };
  return null;
}

function walk(value: unknown, visit: (value: unknown) => void): void { visit(value); if (Array.isArray(value)) for (const item of value) walk(item, visit); else if (value && typeof value === "object") for (const item of Object.values(value)) walk(item, visit); }
function findObjectsByKey(value: unknown, key: string): unknown[] { const found: unknown[] = []; walk(value, (current) => { if (current && typeof current === "object" && !Array.isArray(current) && Object.prototype.hasOwnProperty.call(current, key)) found.push((current as Record<string, unknown>)[key]); }); return found; }
